name: SSH into VM and update

on:
  push:
    branches:
      - deploy_ekto

jobs:
  deploy_ekto:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and Update deploy_ekto Worktree
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/deploy_ekto
            ./update.sh deploy_ekto
            echo "Deploy_ekto update script successful!"
