name: SSH into VM and update

on:
  push:
    branches:
      - deploy_gradia

jobs:
  deploy_gradia:
    runs-on: ubuntu-latest

    steps:
      - name: SSH into VM and Update deploy_gradia Worktree
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/deploy_gradia
            ./update.sh deploy_gradia
            echo "Deploy_gradia update script successful!"
