name: SSH into VM and update
on:
  push:
    branches:
      - deploy_gradia
      - deploy_ekto
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=${GITHUB_REF#refs/heads/}" >> $GITHUB_ENV

      - name: SSH into VM and Update
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.DROPLET_IP }}
          username: ${{ secrets.DROPLET_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd ~/${{ env.BRANCH_NAME }}
            ./update.sh
            echo "${{ env.BRANCH_NAME }} update script successful!"
