name: Run linter on deploy

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5

    - name: Run linter
      run: uv run ruff check
